In [1]:
import numpy as np

In [2]:
A = np.array([[5,1],
              [3,3]])

In [3]:
eigVals, eigVecs = np.linalg.eig(A) # eigVals : 고유값, eigVecs: 고유벡터

In [4]:
eigVals

array([6., 2.])

In [5]:
eigVecs 

array([[ 0.70710678, -0.31622777],
       [ 0.70710678,  0.9486833 ]])

v1 = (0.70710678, 0.70710678)\
v2 = (-0.31622777, 0.9486833)

In [6]:
v1 = eigVecs[:, 0]
v2 = eigVecs[:, 1]

In [7]:
np.linalg.norm(v1) 

0.9999999999999999

결과 값 0.9999999999999999 = 1 동일함

In [8]:
np.linalg.norm(v2)

0.9999999999999999

## When the determinant = 0

In [11]:
singular_mat = np.array([[1, 2],
                        [2, 4]])

In [12]:
np.linalg.eig(singular_mat)

(array([0., 5.]),
 array([[-0.89442719, -0.4472136 ],
        [ 0.4472136 , -0.89442719]]))

In [13]:
np.linalg.det(singular_mat)

0.0

In [14]:
np.linalg.matrix_rank(singular_mat)

1

In [15]:
np.linalg.inv(singular_mat)

LinAlgError: Singular matrix

Singular matrix => full rank matrix X

## 대칭행렬의 고유벡터는 서로 수직

In [16]:
symm_mat = np.array([[1, 2],
                [2, 1]])

In [17]:
evalues, evectors= np.linalg.eig(symm_mat)

In [18]:
evectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [19]:
np.dot(evectors[:,0], evectors[:,1])

0.0

사이각이 90도 즉, cos세타 값이 0이기 때문

When A is a symmetric matrix, then V-1 = V.T

In [20]:
evectors.T

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [21]:
np.linalg.inv(evectors)

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

## Eigendecomposition

In [22]:
A = np.array([[5,1],
              [3,3]])

In [27]:
eigVals, V = np.linalg.eig(A)

In [25]:
v1 = V[:, 0]
v2 = V[:, 1]

In [26]:
np.dot(A, v1)

array([4.24264069, 4.24264069])

In [28]:
eigVals[0]*v1

array([4.24264069, 4.24264069])

In [31]:
np.dot(A, v2)

array([-0.63245553,  1.8973666 ])

In [32]:
eigVals[1]*v2

array([-0.63245553,  1.8973666 ])

In [33]:
np.linalg.matrix_rank(V)

2

In [34]:
L = np.diag(eigVals) # diag : 대각행렬
L # 람다

In [35]:
np.dot(np.dot(V,L),np.linalg.inv(V))

array([[5., 1.],
       [3., 3.]])