# 넘파이

## 넘파이 배열 생성

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [3]:
print(arr1)

[1 2 3 4 5]


In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(arr3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


-----

### 배열 생성 및 초기화 함수

In [10]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [11]:
b = np.zeros((3, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [15]:
b = np.ones((3, 3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
a = np.full((3,3), 1.5)
print(a)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [17]:
a = np.eye(3) #단위행렬
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


-----

### 생성한 값으로 배열 생성

In [18]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [19]:
a = np.arange(1, 21, 5)
a

array([ 1,  6, 11, 16])

In [20]:
a = np.linspace(0, 10, 5) #균일한 간격
a

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
a = np.logspace(np.log10(10), np.log10(100), 5) #로그 스케일로 지정된 범위에서 균일한 간격
a

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [7]:
a = np.logspace(1, 2, 5)
a

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

-----

### 난수 기반으로 배열 생성

In [24]:
a = np.random.random() #0~1 사이의 실수
a

0.5307650507262124

In [25]:
a = np.random.random((4, 4)) 
a

array([[0.37584889, 0.63221488, 0.42730968, 0.59573081],
       [0.8638989 , 0.42405571, 0.22387856, 0.34281517],
       [0.81620158, 0.79351974, 0.16745755, 0.60485285],
       [0.28047349, 0.25662612, 0.0138188 , 0.60780315]])

In [26]:
a = np.random.randint(1, 10) #랜덤 정수
a

3

In [27]:
a = np.random.randint(1, 10, (4, 4))
a

array([[9, 7, 3, 4],
       [4, 7, 9, 9],
       [9, 3, 6, 6],
       [6, 5, 9, 5]])

In [28]:
a = np.random.rand(3, 3) 
a

array([[0.84650459, 0.49624456, 0.89701803],
       [0.33685756, 0.5082549 , 0.62283921],
       [0.85318085, 0.09180685, 0.79526076]])

In [29]:
a = np.random.randn(3, 3) #표준정규분포
a

array([[ 0.3621909 ,  0.95512518, -1.26128222],
       [-1.25860869, -2.21594611,  0.25706152],
       [-0.1404212 ,  0.22405143, -0.40547938]])

----

## 넘파이 배열 조회

### 넘파이 배열 속성(함수x) 정보

In [102]:
arr = np.arange(1, 6)
arr

array([1, 2, 3, 4, 5])

In [103]:
arr.ndim

1

In [104]:
arr.shape

(5,)

In [105]:
arr.dtype

dtype('int64')

In [106]:
arr.size

5

In [3]:
arr.itemsize

8

In [4]:
arr.nbytes

40

In [109]:
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [110]:
arr2.ndim

2

In [111]:
arr2.shape

(2, 3)

In [112]:
arr2.dtype

dtype('int64')

In [113]:
arr2.size

6

In [114]:
arr2.itemsize

8

In [115]:
arr2.nbytes

48

----

### 배열의 인덱싱과 슬라이싱

In [61]:
arr

array([1, 2, 3, 4, 5])

In [62]:
arr[0]

1

In [63]:
arr[-1]

5

In [64]:
arr[0] = 0
arr

array([0, 2, 3, 4, 5])

In [66]:
arr2d = np.arange(9).reshape(3, 3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
arr2d[0,1]

1

In [68]:
arr2d[0]

array([0, 1, 2])

In [69]:
arr2d[0,0] = 10

In [71]:
arr2d

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [72]:
arr

array([0, 2, 3, 4, 5])

In [73]:
arr[:3]

array([0, 2, 3])

In [74]:
arr[1:]

array([2, 3, 4, 5])

In [75]:
arr[-2:]

array([4, 5])

In [76]:
arr[:-3]

array([0, 2])

In [77]:
arr[::2]

array([0, 3, 5])

In [78]:
arr[::-1]

array([5, 4, 3, 2, 0])

In [80]:
a2 = np.arange(1,25).reshape(4,6)
a2


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [81]:
a2[1]

array([ 7,  8,  9, 10, 11, 12])

In [83]:
a2[1:3, 1:5] 

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17]])

In [84]:
a2[1,:] 

array([ 7,  8,  9, 10, 11, 12])

In [85]:
a2[:,1] 

array([ 2,  8, 14, 20])

In [86]:
a2[:3, :3] 

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [87]:
a2[:2, :] 

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [88]:
a2[:2, ::-1] #행 역순

array([[ 6,  5,  4,  3,  2,  1],
       [12, 11, 10,  9,  8,  7]])

In [89]:
a2[::-1, ::-1] #행 역순, 열 역순

array([[24, 23, 22, 21, 20, 19],
       [18, 17, 16, 15, 14, 13],
       [12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [90]:
a2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [91]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [92]:
b = [True, False, False, True, False] #불린인덱싱

In [93]:
a[b]

array([1, 4])

In [94]:
a = np.arange(11)

In [95]:
a < 5 

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [96]:
a[a < 5] #비교 연산자 사용

array([0, 1, 2, 3, 4])

In [97]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [98]:
a[a % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [99]:
a[(a > 5) & (a <11)] #and

array([ 6,  7,  8,  9, 10])

In [100]:
a[(a > 9) | (a < 5)] #or

array([ 0,  1,  2,  3,  4, 10])

In [101]:
a[~(a % 3 == 0)] # ~() : ()를 제외하고

array([ 1,  2,  4,  5,  7,  8, 10])

---

## 배열의 연산

In [2]:
a = np.arange(1, 11)
b = np.arange(1, 11)

In [3]:
list_a = list(a)
list_b = list(b)

In [6]:
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
print(list_a)
print(list_b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


----

### 산술 연산

In [8]:
a + b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
list_a + list_b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [10]:
np.add(a, b) #더하기

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
a - b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.subtract(a, b) #빼기

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
a * b

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [14]:
np.multiply(a, b) #곱하기

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [15]:
a / b

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.divide(a, b) #나누기

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

---

### 기타 연산

In [17]:
np.exp(a) #지수

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [18]:
np.sqrt(a) #제곱근

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [19]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [20]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [21]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501,
       -0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [22]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [23]:
np.log10(a)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

---

### 집계 함수

In [25]:
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a.sum()

45

In [29]:
a.sum(axis = 0) #행을 기준으로 열방향으로 집계가 된다.

array([12, 15, 18])

In [30]:
a.sum(axis = 1) #열을 기준으로 행방향으로 집계가 된다.

array([ 6, 15, 24])

In [31]:
a.max()

9

In [32]:
np.max(a)

9

In [33]:
a.max(axis = 0)

array([7, 8, 9])

In [34]:
np.max(a, axis = 0)

array([7, 8, 9])

In [35]:
a.min()

1

In [36]:
np.min(a)

1

In [37]:
a.min(axis = 1)

array([1, 4, 7])

In [38]:
np.min(a, axis = 1)

array([1, 4, 7])

In [39]:
a.mean()

5.0

In [40]:
np.mean(a)

5.0

In [41]:
a.mean(axis = 0)

array([4., 5., 6.])

In [42]:
np.mean(a, axis = 0)

array([4., 5., 6.])

In [ ]:
a.median() #중앙값은 np.median()을 사용

In [43]:
np.median(a)

5.0

In [44]:
np.median(a, axis = 1)

array([2., 5., 8.])

In [45]:
a.std()

2.581988897471611

In [46]:
np.std(a)

2.581988897471611

In [47]:
a.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [48]:
np.std(a, axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

---

### 브로드캐스팅 연산

In [49]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 1, 1, 1, 1])

In [50]:
x + y

array([2, 3, 4, 5, 6])

In [51]:
y = 1 #스칼라

In [52]:
x + y #브로드캐스팅 연산

array([2, 3, 4, 5, 6])

In [54]:
a = np.arange(1, 25).reshape(4, 6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [55]:
a + 100

array([[101, 102, 103, 104, 105, 106],
       [107, 108, 109, 110, 111, 112],
       [113, 114, 115, 116, 117, 118],
       [119, 120, 121, 122, 123, 124]])

In [56]:
np.full_like(a, 100) #a와 같은 크기의 100으로 채워진 배열 생성

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [58]:
a = np.arange(5).reshape((1, 5)) #(( )) : 2차원으로 만들어주기 위함
a

array([[0, 1, 2, 3, 4]])

In [59]:
b = np.arange(5).reshape((5, 1))
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [60]:
a + b #브로드캐스팅 연산

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

---

### 벡터 연산

In [61]:
import time

In [62]:
a = np.arange(10000000)
result = 0

In [63]:
s = time.time() #시작 시간
for v in a:
    result += v
e = time.time() #종료 시간
print(result, e - s) 

49999995000000 2.181763172149658


In [64]:
s = time.time()
result = np.sum(a)
e = time.time()
print(result, e - s)

49999995000000 0.017936229705810547


In [ ]:
#np.set_printoptions() : 출력 옵션 설정

---

## 배열 변환

### 전치(Transpose)

In [66]:
a = np.random.randint(1, 10, (3, 3))
a

array([[5, 4, 6],
       [1, 4, 8],
       [2, 6, 6]])

In [67]:
a.T

array([[5, 1, 2],
       [4, 4, 6],
       [6, 8, 6]])

---

### 배열 형태 변경

In [69]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
b = a.ravel() #1차원 배열로 만드는 메서드
b

array([1, 2, 3, 4, 5, 6])

In [73]:
b[0] = 10
b

array([10,  2,  3,  4,  5,  6])

In [74]:
a #원본도 반영됨

array([[10,  2,  3],
       [ 4,  5,  6]])

In [75]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
y = x.reshape(4, 5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [79]:
x[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [80]:
y #원본도 반영됨

array([[10,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
list_data = [1, 2, 3, 4, 5, 6]
list_data.reshpae(3, 2) #list는 reshape() 메서드를 사용할 수 없다. 

AttributeError: 'list' object has no attribute 'reshpae'

리스트는 reshape이 불가능

In [89]:
ndarray_data = np.array(list_data)
data = ndarray_data.reshape(3, 2)
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
list_data[0] = 10

In [92]:
list_data

[10, 2, 3, 4, 5, 6]

In [3]:
ndarray_data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
ndarray_data #원본 반영 x 

array([1, 2, 3, 4, 5, 6])

In [91]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

---

### 배열 요소 추가/삭제

- ndarray.resize( ) : 원본 배열의 형태를 바꾸는 메서드

In [94]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [96]:
y = x.reshape(5, 4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [97]:
y2 = np.resize(x, (5, 4))
y2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [98]:
y = x.reshape(5, 6)
y

ValueError: cannot reshape array of size 20 into shape (5,6)

In [99]:
y2 = np.resize(x, (5, 6))
y2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8,  9]])

In [100]:
y = x.reshape(5, 3)
y

ValueError: cannot reshape array of size 20 into shape (5,3)

In [101]:
y2 = np.resize(x, (5, 3))
y2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [102]:
x[0] = 10
x

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [103]:
y

array([[10,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [104]:
y2 #resize는 원래 메모리와 공유(연동)하지 않는다

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

reshape과 resize의 차이점 : reshape은 크기가 맞아야하지만 resize는 상관없음. 그리고 reshape은 원본 메모리와 공유하지만 resize는 공유하지 않음

---

- ndarray.append( ) : 배열의 끝에 값을 추가

In [105]:
a = np.arange(3)
a

array([0, 1, 2])

In [106]:
b = np.append(a, 3) #리스트와 동일
b

array([0, 1, 2, 3])

In [109]:
lista = [0, 1, 2]
lista.append(3)
print(lista)

[0, 1, 2, 3]


In [110]:
lista.append([4, 5, 6])
lista

[0, 1, 2, 3, [4, 5, 6]]

In [111]:
np.append(b, [4, 5, 6])

array([0, 1, 2, 3, 4, 5, 6])

여러개 추가할 시 리스트는 중첩되서 추가, 넘파이는 그대로 추가

In [112]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [113]:
b = np.array([[7, 8, 9]])
b

array([[7, 8, 9]])

In [114]:
np.append(a, b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.append(a, b, axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
c = np.array([[0], [0]])
c

array([[0],
       [0]])

In [118]:
np.append(a, c, axis = 1)

array([[1, 2, 3, 0],
       [4, 5, 6, 0]])

넘파이에서 행 또는 열별로 추가 시켜줄때는 크기를 고려해야한다.

---

- ndarray.insert( ) : 특정 위치에 값을 추가

In [122]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [123]:
b = np.insert(a, 1, 5) #a array의 1번째 인덱스에 5를 삽입
b

array([1, 5, 2, 3])

In [124]:
lista

[0, 1, 2, 3, [4, 5, 6]]

In [125]:
lista.insert(1, 5)
lista

[0, 5, 1, 2, 3, [4, 5, 6]]

In [126]:
a = np.array([[1,1], [2,2], [3,3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [127]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [128]:
np.insert(a, 1, 5, axis = 0) #행방향으로 삽입

array([[1, 1],
       [5, 5],
       [2, 2],
       [3, 3]])

In [129]:
np.insert(a, 1, 5, axis = 1) #열방향으로 삽입

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

---

- ndarray.delete( ) : 배열에서 특정 요소를 삭제

In [130]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
np.delete(a, 5)

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11])

In [133]:
np.delete(a, 1, axis = 0) #행방향으로 삭제

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [134]:
np.delete(a, 1, axis = 1) #열방향으로 삭제

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

---

### 배열 결합

- concatenate( )

In [140]:
a1 = np.array([[1, 2, 3]])
a2 = np.array([[4, 5, 6]])
arr = np.concatenate((a1, a2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
arr_axis0 = np.concatenate((a1, a2), axis=0)
arr_axis0

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
arr_axis1 = np.concatenate((a1, a2), axis=1)
arr_axis1

array([[1, 2, 3, 4, 5, 6]])

---

- vstack( ) : 수직으로 배열을 합친다. axis=0

In [143]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.vstack((a1, a2)) #1차원 수직 결합(열방향)

array([[1, 2, 3],
       [4, 5, 6]])

- hstack( ) : 수평으로 배열을 합친다. axis=1

In [144]:
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
np.hstack((a1, a2)) #1차원 수평 결합(행방향)

array([1, 2, 3, 4, 5, 6])

---

### 배열 분리

- hsplit( )

In [145]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [149]:
a_hsplit = np.hsplit(a, 2)
a_hsplit # 행방향 분리 axis = 1

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [147]:
a_hsplit[0]

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

---

- vsplit( )

In [150]:
a_vsplit = np.vsplit(a, 2)
a_vsplit # 열방향 분리 axis = 0

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]